# Generated by Django 5.0.6 on 2026-04-28 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('price', models.PositiveIntegerField(default=0, verbose_name="Narx (so'm)")),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, choices=[('', "Yo'q"), ('hot', 'Hot'), ('new', 'Yangi'), ('sale', 'Chegirma')], default='', max_length=8)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('weight', models.CharField(blank=True, default='', max_length=32)),
                ('stock', models.PositiveIntegerField(default=15, verbose_name='Qoldiq')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
